#!/bin/bash

echo "#ENV" > ./.env

echo DOCKER_USERNAME=$DOCKER_USERNAME >> ./.env

echo GITHUB_USERNAME=$GITHUB_USERNAME >> ./.env
echo GITHUB_EMAIL=$GITHUB_EMAIL >> ./.env
echo GITHUB_JENKINS_TOKEN=$GITHUB_JENKINS_TOKEN >> ./.env
echo GITHUB_PACKAGE_TOKEN=$GITHUB_PACKAGE_TOKEN >> ./.env
echo GITHUB_ARTIFACTORY_URL=$GITHUB_ARTIFACTORY_URL >> ./.env

echo SONAR_DB=$SONAR_DB >> ./.env
echo SONAR_DB_USER=$SONAR_DB_USER >> ./.env
echo SONAR_DB_PASSWORD=$SONAR_DB_PASSWORD >> ./.env
echo SONAR_JDBC_URL=$SONAR_JDBC_URL >> ./.env

echo JFROG_DB=$JFROG_DB >> ./.env
echo JFROG_DB_USER=$JFROG_DB_USER >> ./.env
echo JFROG_DB_PASSWORD=$JFROG_DB_PASSWORD >> ./.env
echo JF_SHARED_DATABASE_TYPE=$JF_SHARED_DATABASE_TYPE >> ./.env
echo JF_SHARED_DATABASE_DRIVER=$JF_SHARED_DATABASE_DRIVER >> ./.env
echo JF_SHARED_DATABASE_URL=$JF_SHARED_DATABASE_URL >> ./.env

echo CONCOURSE_DB=$CONCOURSE_DB >> ./.env
echo CONCOURSE_DB_HOST=CONCOURSE_DB_HOST >> ./.env
echo CONCOURSE_DB_PORT=$CONCOURSE_DB_PORT >> ./.env
echo CONCOURSE_DB_USER=$CONCOURSE_DB_USER >> ./.env
echo CONCOURSE_DB_PASSWORD=$CONCOURSE_DB_PASSWORD >> ./.env
echo CONCOURSE_EXTERNAL_URL=$CONCOURSE_EXTERNAL_URL >> ./.env
echo CONCOURSE_CLUSTER_NAME=$CONCOURSE_CLUSTER_NAME >> ./.env
echo CONCOURSE_ADD_LOCAL_USER=$CONCOURSE_ADD_LOCAL_USER >> ./.env
echo CONCOURSE_ADD_LOCAL_PASSWORD=$CONCOURSE_ADD_LOCAL_PASSWORD >> ./.env
echo CONCOURSE_MAIN_TEAM_LOCAL_USER=$CONCOURSE_MAIN_TEAM_LOCAL_USER >> ./.env
echo CONCOURSE_TSA_HOST=$CONCOURSE_TSA_HOST >> ./.env
